<div class="loading_anim_2" style="height: 100vh; width: 100%; position: fixed; top: 0; z-index: 10; background-color: #222f3e; display: block;">
  <div class="loading_anim_image" style="text-align: center; height: 100vh; width: 100vw; position: absolute;">
    <img src="<?php echo SITE_URL;?>/images/loading_text.svg" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -110px); filter: grayscale(100%);">
  </div>
  <div class="loadingio-spinner-ellipsis-qhjea9b3zt" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><div class="ldio-b7u42gltcqr">
  <div></div><div></div><div></div><div></div><div></div>
  </div></div>
  <style type="text/css">
  @keyframes ldio-b7u42gltcqr {
     0% { transform: translate(12.66px,84.39999999999999px) scale(0); }
    25% { transform: translate(12.66px,84.39999999999999px) scale(0); }
    50% { transform: translate(12.66px,84.39999999999999px) scale(1); }
    75% { transform: translate(84.39999999999999px,84.39999999999999px) scale(1); }
   100% { transform: translate(156.14px,84.39999999999999px) scale(1); }
  }
  @keyframes ldio-b7u42gltcqr-r {
     0% { transform: translate(156.14px,84.39999999999999px) scale(1): }
   100% { transform: translate(156.14px,84.39999999999999px) scale(0); }
  }
  @keyframes ldio-b7u42gltcqr-c {
     0% { background: #3be8b0 }
    25% { background: #ffb900 }
    50% { background: #6a67ce }
    75% { background: #1aafd0 }
   100% { background: #3be8b0 }
  }
  .ldio-b7u42gltcqr div {
    position: absolute;
    width: 42.199999999999996px;
    height: 42.199999999999996px;
    border-radius: 50%;
    transform: translate(84.39999999999999px,84.39999999999999px) scale(1);
    background: #3be8b0;
    animation: ldio-b7u42gltcqr 5.882352941176471s infinite cubic-bezier(0,0.5,0.5,1);
  }
  .ldio-b7u42gltcqr div:nth-child(1) {
    background: #1aafd0;
    transform: translate(156.14px,84.39999999999999px) scale(1);
    animation: ldio-b7u42gltcqr-r 1.4705882352941178s infinite cubic-bezier(0,0.5,0.5,1), ldio-b7u42gltcqr-c 5.882352941176471s infinite step-start;
  }.ldio-b7u42gltcqr div:nth-child(2) {
    animation-delay: -1.4705882352941178s;
    background: #3be8b0;
  }.ldio-b7u42gltcqr div:nth-child(3) {
    animation-delay: -2.9411764705882355s;
    background: #1aafd0;
  }.ldio-b7u42gltcqr div:nth-child(4) {
    animation-delay: -4.411764705882353s;
    background: #6a67ce;
  }.ldio-b7u42gltcqr div:nth-child(5) {
    animation-delay: -5.882352941176471s;
    background: #ffb900;
  }
  .loadingio-spinner-ellipsis-qhjea9b3zt {
    width: 211px;
    height: 130px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-b7u42gltcqr {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-b7u42gltcqr div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
  </style>
</div>