<div class="loading_anim" style="height: 100vh; width: 100%; position: fixed; top: 0; z-index: 10; background-color: rgba(52, 73, 94, 0.5); display: none;">
	<div class="loadingio-spinner-ripple-k8oyv9x4ic" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><div class="ldio-8kil1102ff9">
<div></div><div></div>
</div></div>
<style type="text/css">

@keyframes ldio-8kil1102ff9 {
  0% {
    top: 95.47999999999999px;
    left: 95.47999999999999px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 15.19px;
    left: 15.19px;
    width: 160.57999999999998px;
    height: 160.57999999999998px;
    opacity: 0;
  }
}

.ldio-8kil1102ff9 div {
  position: absolute;
  border-width: 13.02px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-8kil1102ff9 1.4492753623188404s cubic-bezier(0,0.2,0.8,1) infinite;
}

.ldio-8kil1102ff9 div:nth-child(1) {
  border-color: #e90c59
}

.ldio-8kil1102ff9 div:nth-child(2) {
  border-color: #46dff0;
  animation-delay: -0.7246376811594202s;
}

.loadingio-spinner-ripple-k8oyv9x4ic {
  width: 217px;
  height: 217px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-8kil1102ff9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-8kil1102ff9 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
</div>


